######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 8 16:20:35 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

unix:MOC_DIR=.tmp
unix:OBJECTS_DIR=.tmp
unix:UI_DIR=.tmp

QT += widgets 

# Input
HEADERS += table.h
SOURCES += main.cpp table.cpp
